name: Salesforce plugin CI
 
on:
   push:
     branches: [ "main" ]
   pull_request:
     branches: [ "main" ]
jobs:
   build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
     - name: Build tool setup Stage
       uses: actions/setup-java@v3
       with:
         java-version: '17'
         distribution: 'temurin'
         cache: maven 
         
     - name: Build tool setup Stage
       run: mvn clean install
       
